"use strict";
var KinkyDungeonMapParams = [

	{//DungeonName0,-Graveyard-
		"background" : "RainyForstPathNight",
		"openness" : 3, // Openness of rooms
		"density" : 3, // Density of tunnels (inverse of room spawn chance)
		"doodadchance" : 0.16,
		"barchance" : 0.03,
		"brightness" : 8,
		"chestcount" : 11,	// per thousand tile
		"shrinecount" : 12,	// per thousand tile
		"ghostcount" : 1,
		"doorchance" : 0.67,
		"nodoorchance" : 0.1,
		"doorlockchance" : -0.1,
		"trapchance" : 0.3,
		"grateChance" : 0.7,
		"rubblechance" : 0.9,
		"brickchance" : 0.1,

		"traps": [
			{Name: "Skeletons", Level: 0, Power: 6, Weight: 100},
			{Name: "Bandits", Level: 0, Power: 1, Weight: 30},
			{Name: "Random", Level: 0, Power: 2, Weight: 30},
		],

		"min_width" : 19,
		"max_width" : 39,
		"min_height" : 11,
		"max_height" : 21,

		"enemytags": [
			{tag:"zombie", weight: 6}, 
			{tag:"skeleton", weight: 4}, 
			{tag:"ghost", weight: 1}, 
			{tag:"bandit", weight: 2}, 
			{tag:"beast", weight: 3}, 
			{tag:"witch", weight: 1},
		],

		"defeat_restraints": [
			{Name: "WristShackles", Level: 0},
			{Name: "HighsecShackles", Level: 10},
			{Name: "HighsecBallGag", Level: 20},
			{Name: "PrisonBelt", Level: 30},
			{Name: "PrisonVibe", Level: 30},
			{Name: "HighsecArmbinder", Level: 40},
			{Name: "LegShackles", Level: 40},
			{Name: "HighsecCollar", Level: 50},
		],
		"defeat_outfit": "Prisoner",
		"shrine_mods": {"Elements":2, "Illusion":2, "Conjure":2, "Lock":-2, "Commerce":2, "Undead":2},
	},

	{// DungeonName1,-Catacombs-
		"background" : "Dungeon",
		"openness" : 0,
		"density" : 2,
		"doodadchance" : 0.1,
		"barchance" : 0.03,
		"brightness" : 6,
		"chestcount" : 12,
		"shrinecount" : 12,
		"ghostcount" : 1,
		"doorchance" : 0.72,
		"nodoorchance" : 0.05,
		"doorlockchance" : -0.07,
		"trapchance" : 0.4,
		"grateChance" : 0.6,
		"rubblechance" : 0.6,
		"brickchance" : 0.35,

		"traps": [
			{Name: "Skeletons", Level: 0, Power: 6, Weight: 100},
			{Name: "Bandits", Level: 0, Power: 2, Weight: 20},
			{Name: "Random", Level: 0, Power: 2, Weight: 60},
		],

		"min_width" : 21,
		"max_width" : 41,
		"min_height" : 11,
		"max_height" : 21,

		"enemytags": [
			{tag:"ancient", weight: 4},
			{tag:"fantasy", weight: 3}, 
			{tag:"skeleton", weight: 4}, 
			{tag:"ghost", weight: 1}, 
			{tag:"bandit", weight: 3}, 
			{tag:"witch", weight: 2}, 
			{tag:"rope", weight: 4}, 
			{tag:"beast", weight: 1}, 
		],
		"defeat_restraints": [
			{Name: "WristShackles", Level: 0},
			{Name: "HighsecShackles", Level: 10},
			{Name: "HighsecBallGag", Level: 20},
			{Name: "PrisonBelt2", Level: 30},
			{Name: "PrisonVibe", Level: 30},
			{Name: "HighsecArmbinder", Level: 40},
			{Name: "LegShackles", Level: 40},
			{Name: "HighsecCollar", Level: 50},
		],
		"defeat_outfit": "Dungeon",
		"shrine_mods": {"Metal":2, "Lock":1},
	},

	{//DungeonName2,-Underground Jungle-
		"openness" : 6,
		"density" : 5,
		"doodadchance" : 0.12,
		"barchance" : 0.03,
		"brightness" : 7,
		"chestcount" : 14,
		"shrinecount" : 10,
		"ghostcount" : 1,
		"doorchance" : 0.2,
		"nodoorchance" : 0.7,
		"doorlockchance" : -0.05,
		"trapchance" : 0.8,
		"grateChance" : 0.7,
		"rubblechance" : 0.55,
		"brickchance" : 0.25,

		"traps": [
			{Name: "Bandits", Level: 0, Power: 3, Weight: 80},
			{Name: "Random", Level: 0, Power: 3, Weight: 60},
		],

		"min_width" : 25,
		"max_width" : 45,
		"min_height" : 13,
		"max_height" : 23,

		"enemytags": [
			{tag:"plant", weight: 5},
			{tag:"fantasy", weight: 4}, 
			{tag:"zombie", weight: 2},
			{tag:"ghost", weight: 1}, 
			{tag:"bandit", weight: 3}, 
			{tag:"witch", weight: 3}, 
			{tag:"rope", weight: 5}, 
			{tag:"beast", weight: 2}, 
		],
		"defeat_restraints": [
			{Name: "WristShackles", Level: 0},
			{Name: "LegShackles", Level: 0},
			{Name: "HighsecShackles", Level: 10},
			{Name: "HighsecBallGag", Level: 20},
			{Name: "PrisonBelt", Level: 30},
			{Name: "PrisonVibe", Level: 30},
			{Name: "HighsecArmbinder", Level: 40},
			{Name: "HighsecLegbinder", Level: 40},
			{Name: "HighsecCollar", Level: 50},
		],
		"defeat_outfit": "LatexPrisoner",
		"shrine_mods": {"Will":2, "Rope":1, "Latex":1, "Delight":1},
	},
	{//DungeonName3,-Lost Temple-
		"openness" : 4,
		"density" : 0,
		"doodadchance" : 0.13,
		"barchance" : 0.03,
		"brightness" : 8,
		"chestcount" : 17,
		"shrinecount" : 17,
		"ghostcount" : 1,
		"doorchance" : 0.7,
		"nodoorchance" : 0.25,
		"doorlockchance" : -0.05,
		"trapchance" : 0.5,
		"rubblechance" : 0.7,
		"brickchance" : 0.1,

		"traps": [
			{Name: "Skeletons", Level: 0, Power: 6, Weight: 60},
			{Name: "Random", Level: 0, Power: 4, Weight: 60},
		],

		"min_width" : 27,
		"max_width" : 47,
		"min_height" : 13,
		"max_height" : 23,

		"lockmult" : 1.5,

		"enemytags": [
			{tag:"zombie", weight: 4}, 
			{tag:"ancient", weight: 4}, 
			{tag:"slime", weight: 2}, 
			{tag:"ghost", weight: 1}, 
			{tag:"witch", weight: 4}, 
			{tag:"rope", weight: 5}, 
			{tag:"bast", weight: 2}, 
		],
		"defeat_restraints": [
			{Name: "WristShackles", Level: 0},
			{Name: "LegShackles", Level: 0},
			{Name: "HighsecShackles", Level: 10},
			{Name: "HighsecBallGag", Level: 20},
			{Name: "PrisonBelt2", Level: 30},
			{Name: "PrisonVibe", Level: 30},
			{Name: "HighsecArmbinder", Level: 40},
			{Name: "HighsecLegbinder", Level: 40},
			{Name: "HighsecCollar", Level: 50},
		],
		"defeat_outfit": "Lingerie",
		"shrine_mods": {"Will":2, "Metal":1, "Silence":3, "Discipline":4},
	},
	/*
	{//DungeonName4,-Fungal Caverns-
		"openness" : 4,
		"density" : 4,
		"doodadchance" : 0.15,
		"barchance" : 0.03,
		"brightness" : 7,
		"chestcount" : 2,
		"shrinecount" : 5,
		"shrinechance" : 0.8,
		"ghostchance" : 0.5,
		"doorchance" : 0.05,
		"nodoorchance" : 0.5,
		"doorlockchance" : -0.05,
		"trapchance" : 0.5,
		"grateChance" : 0.7,
		"rubblechance" : 0.9,
		"brickchance" : 0.2,

		"traps": [
			{Name: "Skeletons", Level: 0, Power: 6, Weight: 100},
		],

		"min_width" : 15,
		"max_width" : 25,
		"min_height" : 15,
		"max_height" : 25,
	},
	{//DungeonName5,-The Bellows-
		"openness" : 1,
		"density" : 1,
		"doodadchance" : 0.05,
		"barchance" : 0.03,
		"brightness" : 8,
		"chestcount" : 3,
		"shrinecount" : 4,
		"shrinechance" : 0.75,
		"ghostchance" : 0.5,
		"doorchance" : 0.67,
		"nodoorchance" : 0.1,
		"doorlockchance" : -0.05,
		"trapchance" : 0.5,
		"grateChance" : 0.7,
		"rubblechance" : 0.7,
		"brickchance" : 0.3,

		"traps": [
			{Name: "Skeletons", Level: 0, Power: 6, Weight: 100},
		],

		"min_width" : 25,
		"max_width" : 51,
		"min_height" : 9,
		"max_height" : 15,

		"lockmult" : 2.0,
	},
	{//DungeonName6,-Underground Desert-
		"openness" : 4,
		"density" : 2,
		"doodadchance" : 0.13,
		"barchance" : 0.03,
		"brightness" : 5,
		"chestcount" : 2,
		"shrinecount" : 6,
		"shrinechance" : 0.5,
		"ghostchance" : 0.5,
		"doorchance" : 0.0,
		"nodoorchance" : 0.3,
		"doorlockchance" : -0.05,
		"trapchance" : 0.5,
		"grateChance" : 0.7,
		"rubblechance" : 0.3,
		"brickchance" : 0.3,

		"traps": [
			{Name: "Skeletons", Level: 0, Power: 6, Weight: 100},
		],

		"min_width" : 25,
		"max_width" : 31,
		"min_height" : 17,
		"max_height" : 25,
	},
	{//DungeonName7,-Kingdom of Ice-
		"openness" : 2,
		"density" : 1,
		"doodadchance" : 0.12,
		"barchance" : 0.03,
		"brightness" : 4,
		"chestcount" : 2,
		"shrinecount" : 5,
		"shrinechance" : 0.8,
		"ghostchance" : 0.5,
		"doorchance" : 0.8,
		"trapchance" : 0.5,
		"grateChance" : 0.7,
		"nodoorchance" : 0.2,
		"rubblechance" : 0.5,
		"brickchance" : 0.7,

		"traps": [
			{Name: "Skeletons", Level: 0, Power: 6, Weight: 100},
		],

		"min_width" : 25,
		"max_width" : 31,
		"min_height" : 11,
		"max_height" : 19,

		"lockmult" : 2.0,
	},
	{//DungeonName8,-Marble Halls-
		"openness" : 4,
		"density" : 0,
		"doodadchance" : 0.12,
		"barchance" : 0.03,
		"brightness" : 8,
		"chestcount" : 4,
		"shrinecount" : 4,
		"shrinechance" : 0.75,
		"ghostchance" : 0.5,
		"doorchance" : 1.0,
		"nodoorchance" : 0.0,
		"doorlockchance" : -0.05,
		"trapchance" : 0.5,
		"grateChance" : 0.7,
		"rubblechance" : 0.7,
		"brickchance" : 0.5,

		"traps": [
			{Name: "Skeletons", Level: 0, Power: 6, Weight: 100},
		],

		"min_width" : 15,
		"max_width" : 21,
		"min_height" : 25,
		"max_height" : 37,

		"lockmult" : 1.5,
	},
	{//DungeonName9,-Ancient Laboratory-
		"openness" : 2,
		"density" : 1,
		"doodadchance" : 0.08,
		"barchance" : 0.03,
		"brightness" : 4,
		"chestcount" : 5,
		"shrinecount" : 3,
		"shrinechance" : 0.75,
		"ghostchance" : 0.5,
		"doorchance" : 1.0,
		"nodoorchance" : 0.0,
		"doorlockchance" : -0.05,
		"trapchance" : 0.5,
		"grateChance" : 0.7,
		"rubblechance" : 0.6,
		"brickchance" : 0.9,

		"traps": [
			{Name: "Skeletons", Level: 0, Power: 6, Weight: 100},
		],

		"min_width" : 25,
		"max_width" : 31,
		"min_height" : 11,
		"max_height" : 19,

		"lockmult" : 4.0,
	},
	{//DungeonName10,-The Mansion-
		"openness" : 10,
		"density" : 0,
		"doodadchance" : 0.05,
		"barchance" : 0.03,
		"brightness" : 100,
		"chestcount" : 0,
		"shrinecount" : 0,
		"shrinechance" : 0.25,
		"ghostchance" : 0.5,
		"doorchance" : 1.0,
		"nodoorchance" : 0.0,
		"doorlockchance" : -0.05,
		"trapchance" : 0.5,
		"grateChance" : 0.7,
		"rubblechance" : 1.0,
		"brickchance" : 0.7,

		"traps": [
			{Name: "Skeletons", Level: 0, Power: 6, Weight: 100},
		],

		"min_width" : 31,
		"max_width" : 31,
		"min_height" : 19,
		"max_height" : 19,

		"lockmult" : 0.0,
	},
	*/
	{//DungeonName11,-Ancient Tombs-
		"background" : "EgyptianTomb",
		"openness" : 1,
		"density" : 3,
		"doodadchance" : 0.25,
		"barchance" : 0.03,
		"brightness" : 5,
		"chestcount" : 15,
		"shrinecount" : 15,
		"ghostcount" : 1.5,
		"doorchance" : 0.4,
		"nodoorchance" : 0.25,
		"doorlockchance" : -0.05,
		"trapchance" : 0.7,
		"grateChance" : 0.7,
		"rubblechance" : 0.7,
		"brickchance" : 0.4,

		"traps": [
			{Name: "Skeletons", Level: 0, Power: 8, Weight: 100},
			{Name: "Random", Level: 0, Power: 5, Weight: 60},
		],

		"min_width" : 21,
		"max_width" : 27,
		"min_height" : 11,
		"max_height" : 17,

		"enemytags": [
			{tag:"zombie", weight: 4}, 
			{tag:"skeleton", weight: 4}, 
			{tag:"ghost", weight: 1}, 
			{tag:"ancient", weight: 4}, 
			{tag:"witch", weight: 3}, 
			{tag:"rope", weight: 6}, 
			{tag:"mummy", weight: 2}, 
		],
		"defeat_restraints": [
			{Name: "WristShackles", Level: 0},
			{Name: "LegShackles", Level: 0},
			{Name: "HighsecShackles", Level: 10},
			{Name: "HighsecBallGag", Level: 20},
			{Name: "PrisonBelt2", Level: 30},
			{Name: "PrisonVibe", Level: 30},
			{Name: "HighsecArmbinder", Level: 40},
			{Name: "HighsecLegbinder", Level: 40},
			{Name: "HighsecCollar", Level: 50},
		],
		"defeat_outfit": "Egyptian",
		"shrine_mods": {"Will":3, "Lock":1},
	},
];
